Fix feature_names check
if feature_names check will result in the error:
ValueError: The truth value of a Index is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().

changed to:
    if feature_names is not None: